### ISSUE TITLE
Error with code_metrics library cause Dawn to exit.

### ISSUE THREAD

**Issue by louim** [thesp0nge/dawnscanner#170]
Hello!

I just installed Dawn `1.5.0` and I'm now getting this error every time I run `dawn`:

It was working correctly before with the `1.4.2` version

Running: `dawn .`

I get:
```
I, [2015-12-09 10:40:15#94040]  INFO -- : dawn v1.5.0 is starting up
.
/Users/louim/.gem/ruby/2.2.3/gems/code_metrics-0.1.3/lib/code_metrics/statistics.rb:30:in `block in calculate_statistics': undefined method `first' for #<CodeMetrics::StatsDirectories:0x007f8ee715aa40> (NoMethodError)
	from /Users/louim/.gem/ruby/2.2.3/gems/code_metrics-0.1.3/lib/code_metrics/statistics.rb:30:in `map'
	from /Users/louim/.gem/ruby/2.2.3/gems/code_metrics-0.1.3/lib/code_metrics/statistics.rb:30:in `calculate_statistics'
	from /Users/louim/.gem/ruby/2.2.3/gems/code_metrics-0.1.3/lib/code_metrics/statistics.rb:11:in `initialize'
	from /Users/louim/.gem/ruby/2.2.3/gems/dawnscanner-1.5.0/lib/dawn/engine.rb:432:in `new'
	from /Users/louim/.gem/ruby/2.2.3/gems/dawnscanner-1.5.0/lib/dawn/engine.rb:432:in `gather_statistics'
	from /Users/louim/.gem/ruby/2.2.3/gems/dawnscanner-1.5.0/lib/dawn/engine.rb:74:in `initialize'
	from /Users/louim/.gem/ruby/2.2.3/gems/dawnscanner-1.5.0/lib/dawn/rails.rb:9:in `initialize'
	from /Users/louim/.gem/ruby/2.2.3/gems/dawnscanner-1.5.0/lib/dawn/core.rb:96:in `new'
	from /Users/louim/.gem/ruby/2.2.3/gems/dawnscanner-1.5.0/lib/dawn/core.rb:96:in `block in detect_mvc'
	from /Users/louim/.gem/ruby/2.2.3/gems/dawnscanner-1.5.0/lib/dawn/core.rb:95:in `each'
	from /Users/louim/.gem/ruby/2.2.3/gems/dawnscanner-1.5.0/lib/dawn/core.rb:95:in `detect_mvc'
	from /Users/louim/.gem/ruby/2.2.3/gems/dawnscanner-1.5.0/bin/dawn:221:in `<top (required)>'
	from /Users/louim/.gem/ruby/2.2.3/bin/dawn:23:in `load'
	from /Users/louim/.gem/ruby/2.2.3/bin/dawn:23:in `<main>'
```

**Comment by thesp0nge** [comment]
Just release 1.5.1 to fix the issue.
Thank you for reporting.

**Comment by aquach** [comment]
Left a note on https://github.com/thesp0nge/dawnscanner/commit/0df1e650be7eb2392ab36d365cf8878528fbe745 about how it appears code_metrics is still being required. Thanks!

**Comment by klippx** [comment]
Yes, it still doesnt work:

```
~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- code_metrics/statistics (LoadError)
~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
~/.rvm/gems/ruby-2.2.3/gems/dawnscanner-1.5.1/lib/dawn/engine.rb:2:in `<top (required)>'
~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
~/.rvm/gems/ruby-2.2.3/gems/dawnscanner-1.5.1/lib/dawn/rails.rb:1:in `<top (required)>'
~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
~/.rvm/gems/ruby-2.2.3/gems/dawnscanner-1.5.1/lib/dawnscanner.rb:5:in `<top (required)>'
~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
~/.rvm/gems/ruby-2.2.3/gems/dawnscanner-1.5.1/bin/dawn:9:in `<top (required)>'
~/.rvm/gems/ruby-2.2.3/bin/dawn:23:in `load'
~/.rvm/gems/ruby-2.2.3/bin/dawn:23:in `<main>'
~/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
```
