### ISSUE TITLE
Uninitialized constant FileUtils

### ISSUE THREAD

**Issue by lukaszsliwa** [thesp0nge/dawnscanner#250]
```bash
lukasz@msi rails-app $ dawn scan .
Resolving dependencies...
[2022-07-27 10:26:52] INFO  (dawn): dawn v2.0.0.rc4 is starting up
[2022-07-27 10:26:52] WARN  (dawn): pattern matching security checks are disabled for Gemfile.lock scan
[2022-07-27 10:26:52] WARN  (dawn): combo security checks are disabled for Gemfile.lock scan
/home/lukasz/.rvm/gems/ruby-3.1.1/gems/dawnscanner-2.0.0.rc4/lib/dawn/knowledge_base.rb:92:in `initialize': uninitialized constant Dawn::KnowledgeBase::FileUtils (NameError)

      FileUtils.mkdir_p(@path)
      ^^^^^^^^^
Did you mean?  FileTest
        from /home/lukasz/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/singleton.rb:127:in `new'
        from /home/lukasz/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/singleton.rb:127:in `block in instance'
        from /home/lukasz/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/singleton.rb:125:in `synchronize'
        from /home/lukasz/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/singleton.rb:125:in `instance'
        from /home/lukasz/.rvm/gems/ruby-3.1.1/gems/dawnscanner-2.0.0.rc4/lib/dawn/engine.rb:178:in `load_knowledge_base'
        from /home/lukasz/.rvm/gems/ruby-3.1.1/gems/dawnscanner-2.0.0.rc4/lib/dawn/cli/dawn_cli.rb:118:in `scan'
        from /home/lukasz/.rvm/gems/ruby-3.1.1/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /home/lukasz/.rvm/gems/ruby-3.1.1/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/lukasz/.rvm/gems/ruby-3.1.1/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /home/lukasz/.rvm/gems/ruby-3.1.1/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /home/lukasz/.rvm/gems/ruby-3.1.1/gems/dawnscanner-2.0.0.rc4/bin/dawn:40:in `<top (required)>'
        from /home/lukasz/.rvm/gems/ruby-3.1.1/bin/dawn:25:in `load'
        from /home/lukasz/.rvm/gems/ruby-3.1.1/bin/dawn:25:in `<main>'
        from /home/lukasz/.rvm/gems/ruby-3.1.1/bin/ruby_executable_hooks:22:in `eval'
        from /home/lukasz/.rvm/gems/ruby-3.1.1/bin/ruby_executable_hooks:22:in `<main>'
lukasz@msi rails-app $
```

**Comment by thesp0nge** [comment]
Hi @lukaszsliwa I merged your patch in a separate branch and I will include soon in main. Please note that it was missing che Changelog reference for your work. Added by myself. :)
